{% set name = "sagemaker_mxnet_container" %}
{% set version = "3.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/sagemaker_mxnet_training/sagemaker_mxnet_training-{{ version }}.tar.gz
  sha256: 41aacad93f8ef7be1d71f05a4f70f14a0b4ecfdaa7577e87c612c548bd986dd6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - retrying
    - sagemaker_containers

test:
  imports:
    - sagemaker_mxnet_container

about:
  home: https://github.com/aws/sagemaker-mxnet-containers
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for creating MXNet containers to run on Amazon SageMaker.
  doc_url: https://pypi.org/project/sagemaker-mxnet-training/
  dev_url: https://github.com/aws/sagemaker-mxnet-containers

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - rluria14
