{% set name = "sagemaker_mxnet_container" %}
{% set version = "4.0.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/sagemaker_mxnet_training/sagemaker_mxnet_training-{{ version }}.tar.gz
  sha256: fcf03a8fd530b70dd3a1a728a454a40853eed47924684af9c1beac18d7273eb4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - retrying
    - sagemaker_containers

test:
  imports:
    - sagemaker_mxnet_container

about:
  home: https://github.com/aws/sagemaker-mxnet-containers
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for creating MXNet containers to run on Amazon SageMaker.
  doc_url: https://pypi.org/project/sagemaker-mxnet-training/
  dev_url: https://github.com/aws/sagemaker-mxnet-containers

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - rluria14
