{% set name = "sagemaker_mxnet_container" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/sagemaker_mxnet_training/sagemaker_mxnet_training-{{ version }}.tar.gz
  sha256: 44118bc2d230ce8b1343934cb9e23a1068043c5b476a09ffd33278fe8dd7914e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - retrying
    - sagemaker_containers

test:
  imports:
    - sagemaker_mxnet_container

about:
  home: https://github.com/aws/sagemaker-mxnet-containers
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for creating MXNet containers to run on Amazon SageMaker.
  doc_url: https://pypi.org/project/sagemaker-mxnet-training/
  dev_url: https://github.com/aws/sagemaker-mxnet-containers

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
